apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-manager-gitops

# ConfigMap generování z externích souborů
configMapGenerator:
- name: frontend-code
  files:
  - server.js=frontend-files/server.js

resources:
  - postgres.yaml
  - backend.yaml
  - frontend.yaml

labels:
  - pairs:
      app.kubernetes.io/name: task-manager
      app.kubernetes.io/version: v3.0.0
      app.kubernetes.io/managed-by: argocd
