apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-manager

resources:
  - postgres.yaml
  - backend.yaml
  - frontend.yaml

commonLabels:
  app.kubernetes.io/name: task-manager
  app.kubernetes.io/version: v1.0.0
  managed-by: argocd