apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-manager-gitops

configMapGenerator:
- name: frontend-server
  files:
  - server.js=frontend-files/server.js
- name: frontend-static
  files:
  - index.html=frontend-files/index.html
  - styles.css=frontend-files/styles.css
  - app.js=frontend-files/app.js

resources:
  - postgres.yaml
  - backend.yaml
  - frontend.yaml
  - postgres-exporter.yaml

labels:
  - pairs:
      app.kubernetes.io/name: task-manager
      app.kubernetes.io/version: v3.0.0
      app.kubernetes.io/managed-by: argocd
