apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-manager-gitops

resources:
  - postgres.yaml
  - backend.yaml
  - frontend.yaml

labels:
  - pairs:
      app.kubernetes.io/name: task-manager
      app.kubernetes.io/version: v2.0.0
      app.kubernetes.io/managed-by: argocd
