apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: postgres-gitops-alerts
  labels:
    release: taikun  # DŮLEŽITÉ
    prometheus: taikun-lma-prometheus
    role: alert-rules
spec:
  groups:
  - name: postgres-gitops.rules
    rules:
    - alert: PostgreSQLExporterDown
      expr: up{job="serviceMonitor/task-manager-gitops/postgres-exporter-gitops/0"} == 0
      for: 2m
      labels:
        severity: critical
        service: postgres-gitops
      annotations:
        summary: "PostgreSQL Exporter is down for GitOps database"
        description: "PostgreSQL Exporter has been down for more than 2 minutes"
    
    - alert: TaskManagerDatabaseConnectionsHigh
      expr: postgres_exporter_database_size_active_connections > 10
      for: 5m
      labels:
        severity: warning
        service: postgres-gitops
      annotations:
        summary: "High number of database connections"
        description: "TaskManager database has {{ $value }} active connections"
    
    - alert: TaskManagerDatabaseSizeGrowing
      expr: increase(postgres_exporter_database_size_database_size_bytes[1h]) > 10485760  # 10MB growth per hour
      for: 30m
      labels:
        severity: warning
        service: postgres-gitops
      annotations:
        summary: "Database growing rapidly"
        description: "TaskManager database grew by {{ $value | humanizeBytes }} in the last hour"
    
    - alert: TaskManagerNoRecentTasks
      expr: time() - postgres_exporter_task_manager_stats_task_timespan_seconds > 86400  # No new tasks for 24h
      for: 1h
      labels:
        severity: info
        service: task-manager
      annotations:
        summary: "No recent task activity"
        description: "No new tasks have been created in the last 24 hours"
