apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-exporter-queries
data:
  queries.yaml: |
    task_manager_stats:
      query: |
        SELECT 
          COUNT(*) as total_tasks,
          COUNT(*) FILTER (WHERE completed = true) as completed_tasks,
          COUNT(*) FILTER (WHERE completed = false) as pending_tasks
        FROM tasks
      metrics:
        - total_tasks:
            usage: "GAUGE"
            description: "Total number of tasks"
        - completed_tasks:
            usage: "GAUGE" 
            description: "Number of completed tasks"
        - pending_tasks:
            usage: "GAUGE"
            description: "Number of pending tasks"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  labels:
    app: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
      - name: postgres-exporter
        image: prometheuscommunity/postgres-exporter:v0.15.0
        ports:
        - containerPort: 9187
          name: metrics
        env:
        - name: DATA_SOURCE_NAME
          value: "postgresql://taskuser:taskpass123@postgres-service:5432/taskmanager?sslmode=disable"
        - name: PG_EXPORTER_EXTEND_QUERY_PATH
          value: "/etc/postgres_exporter/queries.yaml"
        volumeMounts:
        - name: queries-config
          mountPath: /etc/postgres_exporter
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: queries-config
        configMap:
          name: postgres-exporter-queries
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter-service
  labels:
    app: postgres-exporter
spec:
  selector:
    app: postgres-exporter
  ports:
  - name: metrics
    port: 9187
    targetPort: 9187
  type: ClusterIP
