apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task-manager-kustomize-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/richardpolanka/task-manager-gitops.git
    targetRevision: main
    path: environments/dev/task-manager
  
  destination:
    server: https://kubernetes.default.svc
    namespace: task-manager-gitops
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10
