apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-manager-gitops

resources:
  - ../../../base/task-manager

patches:
  - target:
      kind: Deployment
      name: task-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: task-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      version: v1
      kind: Service
      name: task-api-service
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 31003
  - target:
      version: v1
      kind: Service  
      name: task-frontend-service
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 31002

labels:
  - pairs:
      environment: dev
      version: v2.0.0
