apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-manager

resources:
  - ../../../base/task-manager

patchesStrategicMerge:
  - dev-patches.yaml

commonLabels:
  environment: dev

# NodePort pro dev přístup
patchesJson6902:
  - target:
      version: v1
      kind: Service
      name: task-api-service
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 31001
  - target:
      version: v1
      kind: Service  
      name: task-frontend-service
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 31000